package EvenFibonacciNumbers;

import java.util.ArrayList;

//Jerry Huang
//2/14/2016
//Problem 2


/*
* Problem:
* 
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
* By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
public class EvenFibonacciNumbers {
	
	ArrayList<Integer> fibNumbers = new ArrayList<Integer>();

	public static void main(String[] args) {
		
		generateFibNumbers();
	}
	
	public static void generateFibNumbers(){
		
		
		
	}

}
